# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2025-01-21 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Codex',
            new_name='Contact',
        ),
    ]
